spring:
  application:
    name: tencoApi
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:tenco;DB_CLOSE_ON_EXIT=TRUE;MODE=MySQL
    username: sa
    password:
    initialization-mode: embedded # always / embedded / never
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
server:
  port: 8080
logging:
  level:
    org.springframework.web: DEBUG
    jp.co.sunarch: DEBUG
  file: logs/${spring.application.name}.log
